### ISSUE TITLE
handle boolean type values which not wrapped with quotes.

### ISSUE THREAD

**Issue by pjc0247** [jwvg0425/cppson#5]
In standard json format, json can accept 'null', 'false' and 'true' values. but your implementation cannot parse boolean types which not wrapped with quotes("").
## expected result

``` cpp
JSON_CLASS(Foo)
{
public:
  FIELD(bool, b);
}
```

``` json
{
  "b" : true
}
```

**Comment by jwvg0425** [comment]
fixed.
